# Generated by Django 2.2.3 on 2019-10-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Titulo')),
                ('description', models.CharField(max_length=120, verbose_name='Description')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio')),
                ('ciudad', models.CharField(max_length=120, verbose_name='Ciudad')),
                ('views', models.IntegerField()),
                ('reviews', models.IntegerField()),
                ('calification', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
