# Generated by Django 2.2.3 on 2019-10-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tours',
            options={'verbose_name': 'Tour', 'verbose_name_plural': 'Tours'},
        ),
        migrations.AddField(
            model_name='tours',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
