# Generated by Django 2.2.3 on 2019-08-17 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_country', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=40)),
                ('continent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.Continent')),
            ],
        ),
        migrations.AddField(
            model_name='airport',
            name='elevation_ft',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airport',
            name='gps_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='keywords',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='latitude_deg',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=22),
        ),
        migrations.AddField(
            model_name='airport',
            name='local_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='longitude_deg',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=22),
        ),
        migrations.AddField(
            model_name='airport',
            name='scheduled_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='airport',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airport',
            name='wikipedia_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_region', models.CharField(max_length=10)),
                ('municipality', models.CharField(max_length=30)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.Country')),
            ],
        ),
        migrations.AddField(
            model_name='airport',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.Municipality'),
        ),
    ]
