# Generated by Django 2.2.3 on 2019-08-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20190817_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
    ]
