# Generated by Django 2.2.3 on 2019-08-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_auto_20190817_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='municipality',
            field=models.CharField(max_length=60),
        ),
    ]
