# Generated by Django 2.2.3 on 2019-08-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_auto_20190824_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
