# Generated by Django 2.2.3 on 2019-08-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_auto_20190824_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='keywords',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
