# Generated by Django 2.2.3 on 2019-08-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0010_auto_20190824_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='local_code',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
