# Generated by Django 2.2.3 on 2019-08-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0011_auto_20190824_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='keywords',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=260),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=220),
        ),
    ]
