# Generated by Django 2.2.3 on 2019-08-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0012_auto_20190824_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='slug',
            field=models.SlugField(max_length=140, unique=True),
        ),
    ]
