# Generated by Django 2.2.3 on 2019-09-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0014_auto_20190825_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkyMarkets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, verbose_name='Code')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
            ],
        ),
    ]
