# Generated by Django 2.2.3 on 2019-09-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0015_skymarkets'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkyCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Code')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('thousands_separator', models.CharField(max_length=5, verbose_name='ThousandsSeparator')),
                ('symbol_on_left', models.BooleanField(verbose_name='SymbolOnLeft')),
                ('space_setween_amount_and_symbol', models.BooleanField(verbose_name='SpaceBetweenAmountAndSymbol')),
                ('rounding_coefficient', models.PositiveIntegerField(verbose_name='RoundingCoefficient')),
                ('decimal_digits', models.PositiveIntegerField(verbose_name='DecimalDigits')),
            ],
        ),
    ]
