# Generated by Django 2.2.3 on 2019-09-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0016_skycurrency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=8, verbose_name='PlaceId')),
                ('place_name', models.CharField(max_length=120, verbose_name='PlaceName')),
                ('city_id', models.CharField(max_length=20, verbose_name='CityId')),
                ('country_name', models.CharField(max_length=120, verbose_name='CountryName')),
            ],
        ),
    ]
