# Generated by Django 2.2.3 on 2019-09-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0017_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='country_id',
            field=models.CharField(default=2, max_length=60, verbose_name='CountryId'),
            preserve_default=False,
        ),
    ]
